import { StyleSheet } from 'react-native';

import { colors, radii, spacing, typography } from '@/ui';

export const styles = StyleSheet.create({
  camera: { flex: 1 },
  cameraContainer: { flex: 1 },
  case: { color: colors.textMuted, marginTop: 5 },
  casesTitle: { fontWeight: '700', marginTop: 14 },
  card: {
    borderColor: colors.border,
    marginBottom: 16,
    padding: 14,
  },
  centered: {
    alignItems: 'center',
    flex: 1,
    gap: 16,
    justifyContent: 'center',
    padding: 24,
  },
  finalCheck: { gap: 12, marginVertical: 12 },
  footerActions: { gap: 10 },
  day: { borderTopColor: colors.border, borderTopWidth: 1, paddingTop: 8 },
  dayTitle: { fontSize: 16, fontWeight: '800' },
  stockOption: {
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: 4,
    marginTop: 10,
    padding: 12,
  },
  stockOptionTitle: { fontWeight: '700' },
  guide: {
    borderColor: '#fff',
    borderWidth: 2,
    left: '10%',
    padding: 12,
    position: 'absolute',
    right: '10%',
    top: '35%',
  },
  guideText: {
    backgroundColor: '#0009',
    color: '#fff',
    padding: 6,
    textAlign: 'center',
  },
  intro: typography.body,
  name: typography.title,
  period: typography.heading,
  periodHeader: { gap: spacing.xs },
  periodDetail: { ...typography.caption, marginTop: spacing.sm },
  cancelArea: { gap: spacing.xs, marginTop: spacing.lg },
  weekOptions: { gap: spacing.sm },
  weekOption: {
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.md,
  },
  weekOptionSelected: {
    backgroundColor: colors.brandSoft,
    borderColor: colors.brand,
    borderWidth: 2,
  },
  weekOptionTitle: typography.label,
  weekOptionPeriod: { fontSize: 17, fontWeight: '800' },
  progress: { marginBottom: 16, marginTop: 4 },
  success: { backgroundColor: colors.surface },
  successTitle: {
    color: colors.success,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 5,
  },
  total: { fontSize: 17, fontWeight: '700', marginTop: 8 },
  verified: {
    backgroundColor: colors.successSoft,
    borderColor: colors.success,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: 10,
    marginTop: 14,
    padding: 12,
  },
  warning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: 10,
    marginBottom: 16,
    padding: 12,
  },
  warningTitle: { color: colors.warning, fontWeight: '800' },
});
