import { StyleSheet } from 'react-native';

import { colors, layout, radii, typography } from '@/ui';

export const styles = StyleSheet.create({
  darkHeader: {
    backgroundColor: colors.headerDark,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    gap: 9,
    paddingBottom: 16,
    paddingHorizontal: layout.screenPadding,
    paddingTop: 10,
  },
  darkTitle: {
    color: colors.onDark,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 21,
  },
  darkProgress: {
    color: colors.onDarkMuted,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  eyebrow: typography.sectionLabel,
  stockNotice: {
    ...typography.micro,
    textAlign: 'center',
  },
  stepName: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  stepForm: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  stepTiles: { flexDirection: 'row', gap: 9 },
  stepTile: {
    backgroundColor: colors.brandTint,
    borderRadius: radii.tile,
    flex: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  stepTileLabel: {
    color: colors.textTertiary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.9,
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  stepTileValue: {
    ...typography.numeric,
    color: colors.brandPressed,
    fontSize: 17,
    lineHeight: 20,
  },
  finalPanel: {
    alignItems: 'center',
    backgroundColor: colors.successSoft,
    borderRadius: radii.hero,
    gap: 12,
    padding: 20,
  },
  finalMark: {
    alignItems: 'center',
    backgroundColor: colors.success,
    borderRadius: radii.pill,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  finalMarkText: {
    color: colors.onDark,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 30,
  },
  finalTitle: {
    color: colors.success,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
    textAlign: 'center',
  },
  finalBody: {
    color: colors.brandPressed,
    fontSize: 13.5,
    fontWeight: '500',
    lineHeight: 20,
    textAlign: 'center',
  },
  camera: { flex: 1 },
  cameraContainer: { flex: 1 },
  case: { ...typography.detail, marginTop: 5 },
  casesTitle: {
    color: colors.text,
    fontSize: 13.5,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 5,
  },
  centered: {
    alignItems: 'center',
    flex: 1,
    gap: 14,
    justifyContent: 'center',
    padding: 24,
  },
  finalCheck: { gap: 12, marginVertical: 12 },
  footerActions: { gap: 9 },
  day: {
    borderTopColor: colors.hairline,
    borderTopWidth: 1,
    gap: 5,
    paddingTop: 11,
  },
  dayWeekday: {
    color: colors.text,
    fontSize: 14.5,
    fontWeight: '800',
    lineHeight: 18,
  },
  dayDate: {
    color: colors.textTertiary,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 15,
  },
  intro: typography.detail,
  cancelArea: { gap: 6, marginTop: 6 },
  dayTitle: {
    color: colors.text,
    fontSize: 13.5,
    fontWeight: '800',
    lineHeight: 18,
  },
  weekOptions: { gap: 7 },
  weekOption: {
    borderColor: colors.cardBorder,
    borderRadius: radii.tile,
    borderWidth: 1.5,
    gap: 4,
    padding: 12,
  },
  weekOptionSelected: {
    backgroundColor: colors.brandSoft,
    borderColor: colors.brand,
  },
  weekOptionTitle: {
    color: colors.textTertiary,
    fontSize: 10.5,
    fontWeight: '700',
    letterSpacing: 1.1,
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  weekOptionPeriod: {
    ...typography.numeric,
    fontSize: 15.5,
    lineHeight: 19,
  },
  slotTotal: {
    ...typography.numeric,
    color: colors.brandPressed,
    fontSize: 14,
    lineHeight: 18,
  },
  total: {
    ...typography.numeric,
    fontSize: 15,
    lineHeight: 19,
  },
});
