const { withAppBuildGradle } = require('expo/config-plugins');

const SIGNING_MARKER =
  '// PillBox release signing (generated by Expo config plugin)';

const signingEnvironment = `${SIGNING_MARKER}
def releaseKeystorePath = System.getenv("ANDROID_KEYSTORE_PATH")
def releaseKeystorePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
def releaseKeyAlias = System.getenv("ANDROID_KEY_ALIAS")
def releaseKeyPassword = System.getenv("ANDROID_KEY_PASSWORD")
def isReleaseBuild = gradle.startParameter.taskNames.any { taskName ->
    taskName.toLowerCase().contains("release")
}
def missingReleaseSigningValue = [
    releaseKeystorePath,
    releaseKeystorePassword,
    releaseKeyAlias,
    releaseKeyPassword,
].any { value -> value == null || value.isEmpty() }

if (isReleaseBuild && missingReleaseSigningValue) {
    throw new GradleException("Android release signing environment variables are missing")
}

`;

const releaseSigningConfig = `
        release {
            if (!missingReleaseSigningValue) {
                storeFile file(releaseKeystorePath)
                storePassword releaseKeystorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
`;

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error(
        'La configuration de signature Android exige Gradle Groovy.',
      );
    }

    let contents = gradleConfig.modResults.contents;
    if (contents.includes(SIGNING_MARKER)) {
      return gradleConfig;
    }

    const androidBlock = 'android {';
    const androidBlockIndex = contents.indexOf(androidBlock);
    if (androidBlockIndex === -1) {
      throw new Error(
        'Bloc android introuvable dans android/app/build.gradle.',
      );
    }
    contents =
      contents.slice(0, androidBlockIndex) +
      signingEnvironment +
      contents.slice(androidBlockIndex);

    const signingConfigsStart = contents.indexOf('    signingConfigs {');
    const buildTypesStart = contents.indexOf(
      '    buildTypes {',
      signingConfigsStart,
    );
    if (signingConfigsStart === -1 || buildTypesStart === -1) {
      throw new Error('Configuration de signature Gradle introuvable.');
    }

    const signingConfigsEnd = contents.lastIndexOf('    }', buildTypesStart);
    contents =
      contents.slice(0, signingConfigsEnd) +
      releaseSigningConfig +
      contents.slice(signingConfigsEnd);

    const debugSigning = 'signingConfig signingConfigs.debug';
    const releaseSigningIndex = contents.lastIndexOf(debugSigning);
    if (releaseSigningIndex === -1) {
      throw new Error('Signature release Gradle par défaut introuvable.');
    }
    contents =
      contents.slice(0, releaseSigningIndex) +
      'signingConfig signingConfigs.release' +
      contents.slice(releaseSigningIndex + debugSigning.length);

    gradleConfig.modResults.contents = contents;
    return gradleConfig;
  });
};
